export type Table = {
  /** Display label, e.g. "13" or "B". */
  id: string;
  /** Group name, e.g. "Bridesmaids". */
  name: string;
  guests: string[];
};

export const tables: Table[] = [
  {
    id: "B",
    name: "Main Table",
    guests: [
      "Lee Zi Hang",
      "Yin Goh Sher Nee",
      "Alicia Yin",
      "Goh Theng Lai",
      "Yin Thin Koh",
      "Alice Tan",
      "Irena Goh",
      "Jaymes Lee",
      "Ng Siew Han",
      "Livius Lee",
    ],
  },
  {
    id: "13",
    name: "Bridesmaids",
    guests: [
      "Yin Sher Mayne",
      "Yin Sher Li",
      "Yin Ginnie",
      "Fong Chiew Ying",
      "Kamran Rajendran",
      "Melody Kuan Pei San",
      "Gooi Wai Jian",
      "Teh Han Sheryl",
      "Ong Lin Pin",
    ],
  },
  {
    id: "4",
    name: "Groomsmen",
    guests: [
      "Manickam Murugappan",
      "Lam E Shuen",
      "Nancy Teoh",
      "Abu Huraira",
      "Syahriz Kader",
      "Soon Cur Lunn",
      "Kenneth Ung",
      "Aswintguru Sivaguru",
      "Chong Jia Qi",
    ],
  },
  {
    id: "11",
    name: "TRC Group",
    guests: [
      "Lee Zi Ting",
      "Caitlin",
      "Lee Zi Xuan",
      "Lee Zi Thung",
      "Lee Zi Yang",
      "Shawn",
      "Angeline Chan",
      "Jane Lee",
      "Ah Moon",
      "Jordan Tan",
    ],
  },
  {
    id: "12",
    name: "Lee Family",
    guests: [
      "Ken Lee",
      "May Lew",
      "Yuna Lee",
      "Jasper Lee",
      "Janice Lee",
      "Lisa",
      "Lee Zi Xing",
      "Lee Zi Yuan",
      "Stephanie Kong",
      "Lee Zi Feng",
    ],
  },
  {
    id: "14",
    name: "Yin Siblings",
    guests: [
      "Yin Sue Zyan",
      "Kyle Yeoh",
      "Goh Kent Lee",
      "Chow Kit May",
      "Ashton Goh",
      "Alyssa Goh",
      "Joey Yin Chuin Yit",
      "Vivienne",
      "Larissa Yin",
      "Laura",
    ],
  },
  {
    id: "17",
    name: "Yin Family",
    guests: [
      "Yin Thin Poh",
      "Siew Nui",
      "Yin Yung Yen",
      "Yin Joe Lynn",
      "Patricia Yin Chee Eng",
      "Olivier Cane",
      "Alexandre Cane",
      "Chang Joe Son",
      "Enzo Chang",
      "Elaine",
    ],
  },
  {
    id: "16",
    name: "Tan Family",
    guests: [
      "Tan Kok Keong",
      "Ng Yuet Kuan",
      "Tan Yi Chern",
      "Tan Hong Yi",
      "Tan Choo Chye",
      "Tan Chee Han",
      "Tan Chee Ewe",
      "Cheah Siew Tin",
      "Tan Chee Ming",
      "Haven Tan",
    ],
  },
  {
    id: "15",
    name: "Yin Family",
    guests: [
      "Alvin Yin",
      "Maybelline",
      "Yin Jeryl",
      "Jefferson Yin",
      "William Yin Thin Wooi",
      "Dorothy Loke",
      "Yin Thien Hai",
      "Yin Thin Song",
    ],
  },
  {
    id: "18",
    name: "Yin Family",
    guests: [
      "Shao Huay",
      "Kelsi",
      "Keira",
      "Karl",
      "Leia",
      "Tommy Leong",
      "Chrissy",
      "Sheldon Leong",
    ],
  },
  {
    id: "7",
    name: "LEADERland",
    guests: [
      "Sophie Tan Mee Yee",
      "Lee Phie Ting",
      "Lee Her Xuan",
      "Lee Min Hoong",
      "Winnie Lim",
      "Steve Ngan",
      "Woo Lee Siang",
      "Oh Li Fang",
      "Lynn Chang",
      "Teoh Kai Thing",
    ],
  },
  {
    id: "3",
    name: "LEADERland",
    guests: [
      "Chow Zhi Yi",
      "Carinne Yeoh",
      "Chan Hong Ming",
      "Ernest Chan Khai En",
      "Zenem Low",
      "Sirius Lee",
      "Hailey Cheng",
      "Ooi Way Loon",
      "Ooi Yi Hong",
      "June Tan Si Jia",
    ],
  },
  {
    id: "10",
    name: "LEADERland",
    guests: [
      "Chua Eng Wei",
      "Nancy Yip",
      "Alfred Sin",
      "Lim Chin Heng",
      "Venessa Khoo",
      "Hor Su Wei",
      "Maybel Lim",
      "Lim Cheng Ann",
      "Chew King Hock",
    ],
  },
  {
    id: "21",
    name: "LEADERland",
    guests: [
      "Gayathiri A/P Ganasan",
      "Sharon Pedley",
      "Jessica Neoh Su Faye",
      "Cindy Ding",
      "Joey Wong",
      "Victor Loh",
      "Ong Kean Tatt",
      "Brendon Tan",
    ],
  },
  {
    id: "1",
    name: "Zh's Friends",
    guests: [
      "Kok Xun",
      "Henry Chee",
      "Lam Weng Jun",
      "Jonathan Tey",
      "Razlan",
      "Lim Zhi Yi",
      "Teh Zhi Hern",
    ],
  },
  {
    id: "5",
    name: "Zh's Friends",
    guests: [
      "Yap Zi Jian",
      "Ron Edward Sioson",
      "Chow Yew Lim",
      "Russell Ng",
      "Joseph Gan",
    ],
  },
  {
    id: "2",
    name: "Zh's Friends",
    guests: [
      "Cheah Chor Gene",
      "Mackhem Chuah",
      "Nicholas Lim",
      "Khoo Lay Ken",
      "Matthew Ian Clyde",
      "Jarryl Lim",
      "Kenny Cheng",
    ],
  },
  {
    id: "6",
    name: "Zh's Friends",
    guests: [
      "Lim Chiew Tung",
      "Tay Qing Yun",
      "Teoh Wei Sheng",
      "Jovin Ooi",
      "Kenjo Chong",
      "Hooi Jay Shen",
      "Yap Jun Hao",
      "Eugene Khoo",
    ],
  },
];
